export const engagementData = [
  { date: "Jan 1", views: 12400, likes: 980, comments: 124, er: 3.2 },
  { date: "Jan 8", views: 18200, likes: 1420, comments: 198, er: 4.1 },
  { date: "Jan 15", views: 15800, likes: 1180, comments: 156, er: 3.7 },
  { date: "Jan 22", views: 24600, likes: 2100, comments: 312, er: 5.8 },
  { date: "Jan 29", views: 21000, likes: 1780, comments: 245, er: 4.9 },
  { date: "Feb 5", views: 28400, likes: 2560, comments: 398, er: 6.3 },
  { date: "Feb 12", views: 32100, likes: 3020, comments: 467, er: 7.1 },
  { date: "Feb 19", views: 29800, likes: 2780, comments: 421, er: 6.7 },
  { date: "Feb 26", views: 38600, likes: 3890, comments: 578, er: 8.2 },
  { date: "Mar 5", views: 42100, likes: 4200, comments: 634, er: 8.9 },
  { date: "Mar 12", views: 45800, likes: 4680, comments: 712, er: 9.4 },
  { date: "Mar 19", views: 51200, likes: 5340, comments: 823, er: 10.2 },
];

export const platformData = [
  { platform: "TikTok", followers: 128400, growth: 12.4, er: 8.7, posts: 234, color: "#69C9D0" },
  { platform: "Instagram", followers: 84200, growth: 6.1, er: 4.2, posts: 312, color: "#E1306C" },
  { platform: "YouTube", followers: 52600, growth: 18.3, er: 5.9, posts: 87, color: "#FF0000" },
  { platform: "Telegram", followers: 31800, growth: 22.7, er: 12.4, posts: 567, color: "#229ED9" },
];

export const topPosts = [
  {
    id: "1",
    platform: "TikTok",
    title: "5 Morning Habits That Changed My Life",
    views: 2840000,
    likes: 284000,
    comments: 12400,
    shares: 48200,
    er: 12.1,
    date: "Mar 15",
    thumbnail: "https://picsum.photos/seed/post1/80/80",
    type: "viral",
  },
  {
    id: "2",
    platform: "Instagram",
    title: "Minimal productivity setup 2024",
    views: 890000,
    likes: 67200,
    comments: 3400,
    shares: 12800,
    er: 9.4,
    date: "Mar 12",
    thumbnail: "https://picsum.photos/seed/post2/80/80",
    type: "educational",
  },
  {
    id: "3",
    platform: "YouTube",
    title: "I tried $0 vs $10,000 marketing budget",
    views: 1240000,
    likes: 48600,
    comments: 5670,
    shares: 9800,
    er: 5.2,
    date: "Mar 8",
    thumbnail: "https://picsum.photos/seed/post3/80/80",
    type: "entertaining",
  },
  {
    id: "4",
    platform: "TikTok",
    title: "This one tool 10x'd my output",
    views: 1680000,
    likes: 198000,
    comments: 8900,
    shares: 31200,
    er: 14.2,
    date: "Mar 5",
    thumbnail: "https://picsum.photos/seed/post4/80/80",
    type: "viral",
  },
  {
    id: "5",
    platform: "Telegram",
    title: "Weekly AI tools digest #47",
    views: 28400,
    likes: 2100,
    comments: 890,
    shares: 1240,
    er: 15.3,
    date: "Mar 19",
    thumbnail: "https://picsum.photos/seed/post5/80/80",
    type: "educational",
  },
];

export const competitors = [
  {
    id: "c1",
    handle: "@techcreator_pro",
    platform: "TikTok",
    followers: 284000,
    growth: 28.4,
    er: 7.8,
    postsPerWeek: 12,
    avgViews: 124000,
    topFormat: "Tutorial",
    avatar: "https://picsum.photos/seed/comp1/40/40",
  },
  {
    id: "c2",
    handle: "@digitalminds",
    platform: "Instagram",
    followers: 198000,
    growth: 14.2,
    er: 5.4,
    postsPerWeek: 7,
    avgViews: 48000,
    topFormat: "Carousel",
    avatar: "https://picsum.photos/seed/comp2/40/40",
  },
  {
    id: "c3",
    handle: "@growthlab_yt",
    platform: "YouTube",
    followers: 142000,
    growth: 32.1,
    er: 6.9,
    postsPerWeek: 3,
    avgViews: 89000,
    topFormat: "Case Study",
    avatar: "https://picsum.photos/seed/comp3/40/40",
  },
];

export const ideas = [
  {
    id: "i1",
    title: "Why 99% of people fail at building habits",
    category: "Educational",
    tags: ["viral", "psychology", "self-help"],
    priority: "high",
    status: "idea",
    platform: ["TikTok", "YouTube"],
    aiScore: 92,
    createdAt: "2024-03-18",
    notes: "Hook: shocking statistic. Show the 3 hidden reasons backed by neuroscience.",
  },
  {
    id: "i2",
    title: "Day in my life as a content creator making $10k/month",
    category: "Entertaining",
    tags: ["viral", "behind-scenes", "income"],
    priority: "high",
    status: "in-progress",
    platform: ["TikTok", "Instagram"],
    aiScore: 88,
    createdAt: "2024-03-17",
    notes: "Film authentic morning routine. Include real numbers and tools.",
  },
  {
    id: "i3",
    title: "10 AI tools that replace $5000/month in software",
    category: "Educational",
    tags: ["ai", "tools", "productivity"],
    priority: "high",
    status: "idea",
    platform: ["YouTube", "Telegram"],
    aiScore: 96,
    createdAt: "2024-03-16",
    notes: "Compare free AI vs paid tools. Show workflow automation.",
  },
  {
    id: "i4",
    title: "I tested every viral hook formula for 30 days",
    category: "Educational",
    tags: ["copywriting", "hooks", "experiment"],
    priority: "medium",
    status: "idea",
    platform: ["TikTok"],
    aiScore: 84,
    createdAt: "2024-03-15",
    notes: "Track metrics for each hook type. Show results with data.",
  },
  {
    id: "i5",
    title: "The brutal truth about social media growth in 2024",
    category: "Viral",
    tags: ["controversial", "growth", "insights"],
    priority: "high",
    status: "posted",
    platform: ["TikTok", "YouTube"],
    aiScore: 91,
    createdAt: "2024-03-14",
    notes: "Controversial take: engagement > followers. Back with data.",
  },
  {
    id: "i6",
    title: "Notion setup tour for creators (template included)",
    category: "Educational",
    tags: ["notion", "productivity", "template"],
    priority: "low",
    status: "idea",
    platform: ["YouTube", "Instagram"],
    aiScore: 72,
    createdAt: "2024-03-13",
    notes: "Share personal workspace. Include free downloadable template.",
  },
  {
    id: "i7",
    title: "Reacting to my first viral video (cringe warning)",
    category: "Entertaining",
    tags: ["reaction", "nostalgia", "relatable"],
    priority: "medium",
    status: "in-progress",
    platform: ["YouTube", "TikTok"],
    aiScore: 79,
    createdAt: "2024-03-12",
    notes: "Authentic reaction. Show growth journey from 0 to now.",
  },
  {
    id: "i8",
    title: "ChatGPT prompt that writes better than most humans",
    category: "Educational",
    tags: ["ai", "chatgpt", "writing"],
    priority: "high",
    status: "idea",
    platform: ["TikTok", "Telegram"],
    aiScore: 94,
    createdAt: "2024-03-11",
    notes: "Chain-of-thought prompt engineering. Show before/after.",
  },
];

export const calendarEvents = [
  { id: "e1", title: "5 Morning Habits (TikTok)", date: "2024-03-20", status: "posted", platform: "TikTok", priority: "high" },
  { id: "e2", title: "AI Tools Digest #48", date: "2024-03-21", status: "scheduled", platform: "Telegram", priority: "medium" },
  { id: "e3", title: "Minimal Setup Tour", date: "2024-03-22", status: "in-progress", platform: "Instagram", priority: "medium" },
  { id: "e4", title: "ChatGPT Prompt Video", date: "2024-03-25", status: "idea", platform: "TikTok", priority: "high" },
  { id: "e5", title: "10 AI Tools YouTube", date: "2024-03-27", status: "idea", platform: "YouTube", priority: "high" },
  { id: "e6", title: "Day in my life Reel", date: "2024-03-28", status: "in-progress", platform: "Instagram", priority: "high" },
  { id: "e7", title: "Weekly Growth Update", date: "2024-04-01", status: "idea", platform: "Telegram", priority: "low" },
  { id: "e8", title: "Hook Formula Test Results", date: "2024-04-03", status: "idea", platform: "TikTok", priority: "medium" },
  { id: "e9", title: "Notion Template Tour", date: "2024-04-05", status: "idea", platform: "YouTube", priority: "low" },
  { id: "e10", title: "Creator Income Breakdown", date: "2024-04-08", status: "idea", platform: "YouTube", priority: "high" },
];

export const aiInsights = [
  {
    type: "opportunity",
    icon: "🚀",
    title: "Peak performance window detected",
    body: "Your TikTok videos posted between 7–9 PM get 3.2× more views. You've only used this slot 4× this month.",
    action: "Schedule 3 posts this week in the 7–9 PM slot",
    priority: "high",
  },
  {
    type: "warning",
    icon: "⚠️",
    title: "Posting frequency dropped 40%",
    body: "You posted 8 times last week vs 14 the week before. Accounts with consistent posting see 2× faster follower growth.",
    action: "Add 6 posts to your calendar to hit your weekly target",
    priority: "high",
  },
  {
    type: "trend",
    icon: "📈",
    title: "Tutorial format is outperforming",
    body: "Your tutorials get 6.8% ER vs 3.1% for vlogs and 2.4% for product reviews. Tutorial is your #1 format.",
    action: "Create 2 more tutorials this week",
    priority: "medium",
  },
  {
    type: "competitor",
    icon: "🔍",
    title: "Competitor @techcreator_pro is growing 2× faster",
    body: "They post 12× per week vs your 7×. Their hook style 'contrarian takes' gets 40% higher CTR than average.",
    action: "Test 3 contrarian-angle videos this month",
    priority: "medium",
  },
  {
    type: "content",
    icon: "💡",
    title: "AI & productivity niche is trending +34%",
    body: "Searches and engagement for AI productivity content are up 34% this week. Your audience overlaps 78% with this niche.",
    action: "Publish 2 AI-focused videos before the trend peaks",
    priority: "high",
  },
];

export const contentHealthScore = {
  overall: 74,
  consistency: 62,
  engagement: 88,
  growth: 71,
  diversity: 65,
  trending: 84,
};

export const chatMessages = [
  {
    role: "assistant" as const,
    content: "Hi! I'm your AI content strategist. I have full access to your analytics and content performance data. What would you like to know? 🚀",
    timestamp: new Date(Date.now() - 60000 * 10),
  },
  {
    role: "user" as const,
    content: "Why are my views dropping on TikTok this week?",
    timestamp: new Date(Date.now() - 60000 * 8),
  },
  {
    role: "assistant" as const,
    content: `Based on your analytics, I can see a few factors contributing to the drop:

**1. Posting frequency fell by 40%** — You posted 5 times this week vs 12 the week before. TikTok's algorithm favors consistent creators, and your reach likely shrank as a result.

**2. Hook quality dropped** — Your last 3 videos used statement hooks ("Here's how...") while your top performers use curiosity/question hooks ("Why do 99% of people..."). Question hooks have 2.7× higher completion rate for your audience.

**3. You missed peak posting windows** — 3 of your 5 posts this week were published before 3 PM. Your audience is most active 7–10 PM.

**My recommendation:** Post daily for the next 7 days, use curiosity hooks, and schedule everything between 7–9 PM. Based on your historical data, you should recover within 5–7 days.`,
    timestamp: new Date(Date.now() - 60000 * 7),
  },
];
